Add missing cstdint includes
Workflow started failing with multiple:
error: ‘uint32_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?